//! Concept type for memory consolidation (Phase 49).
//!
//! Concepts are summaries of related events, created during "sleep cycles".
//! They are derivable from the ledger and never replace the original events.

use chrono::{DateTime, Utc};
use serde::{Deserialize, Serialize};

use super::ids::EventId;

/// A unique identifier for a Concept.
#[derive(Debug, Clone, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub struct ConceptId(pub ulid::Ulid);

impl ConceptId {
    /// Create a new ConceptId.
    pub fn new() -> Self {
        Self(ulid::Ulid::new())
    }
}

impl Default for ConceptId {
    fn default() -> Self {
        Self::new()
    }
}

impl std::fmt::Display for ConceptId {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        write!(f, "{}", self.0)
    }
}

/// A Concept is a summary of related events.
///
/// Concepts are created during consolidation (sleep cycle) and help reduce
/// noise when searching for relevant memories. They never replace the
/// original events - they are a derived view.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct Concept {
    /// Unique concept ID.
    pub id: ConceptId,

    /// Summary description of the grouped events.
    pub summary: String,

    /// IDs of events this concept summarizes.
    pub event_ids: Vec<EventId>,

    /// Max importance from the source events.
    pub importance: f32,

    /// Tags derived from source events.
    pub tags: Vec<String>,

    /// Project associated with this concept.
    pub project_id: Option<String>,

    /// When the concept was created.
    pub created_at: DateTime<Utc>,

    /// When the concept was last accessed.
    pub last_accessed: DateTime<Utc>,

    /// Semantic embedding vector for similarity search.
    /// Generated by SemanticClient when available.
    pub embedding: Option<crate::representations::EmbeddingVector>,
}

impl Concept {
    /// Create a new concept from a set of events.
    pub fn new(summary: impl Into<String>, event_ids: Vec<EventId>) -> Self {
        Self {
            id: ConceptId::new(),
            summary: summary.into(),
            event_ids,
            importance: 0.5,
            tags: vec![],
            project_id: None,
            created_at: Utc::now(),
            last_accessed: Utc::now(),
            embedding: None,
        }
    }

    /// Set the importance (max from source events).
    pub fn with_importance(mut self, importance: f32) -> Self {
        self.importance = importance;
        self
    }

    /// Set tags.
    pub fn with_tags(mut self, tags: Vec<String>) -> Self {
        self.tags = tags;
        self
    }

    /// Set project.
    pub fn with_project(mut self, project: impl Into<String>) -> Self {
        self.project_id = Some(project.into());
        self
    }

    /// Number of events this concept summarizes.
    pub fn event_count(&self) -> usize {
        self.event_ids.len()
    }

    /// Update last accessed timestamp.
    pub fn touch(&mut self) {
        self.last_accessed = Utc::now();
    }
}
